// product-data.ts
export interface ProductItem {
  id: number;
  title: string;
  category: string;
  city: string;
  district: string;
  location: string;
  date: string;
  thumbnail: string;
  avatar: string;
}

export const PRODUCT_ITEMS: ProductItem[] = [
  {
    id: 1,
    title: "Váy em bé",
    category: "CLOTHES",
    city: "LD",
    district: "Di Linh",
    location: "Di Linh, Lâm Đồng",
    date: "20 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-1.png",
    avatar: "/src/assets/images/avatar-2.png",
  },
  {
    id: 2,
    title: "Áo thun nam",
    category: "CLOTHES",
    city: "HCM",
    district: "Quận 1",
    location: "Quận 1, Hồ Chí Minh",
    date: "25 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-2.png",
    avatar: "/src/assets/images/avatar-3.png",
  },
  {
    id: 3,
    title: "Máy sấy tóc",
    category: "ELEC",
    city: "DN",
    district: "Ngũ Hành Sơn",
    location: "Ngũ Hành Sơn, Đà Nẵng",
    date: "21 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-3.png",
    avatar: "/src/assets/images/avatar-3.png",
  },
  {
    id: 4,
    title: "Cardigan vàng",
    category: "CLOTHES",
    city: "HB",
    district: "Tân Lạc",
    location: "Tân Lạc, Hòa Bình",
    date: "20 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-4.png",
    avatar: "/src/assets/images/avatar-4.png",
  },
  {
    id: 5,
    title: "Quần short",
    category: "CLOTHES",
    city: "DN",
    district: "Ngũ Hành Sơn",
    location: "Ngũ Hành Sơn, Đà Nẵng",
    date: "27 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-5.png",
    avatar: "/src/assets/images/avatar-5.png",
  },
  {
    id: 6,
    title: "Ấm siêu tốc",
    category: "ELEC",
    city: "DN",
    district: "Ngũ Hành Sơn",
    location: "Ngũ Hành Sơn, Đà Nẵng",
    date: "15 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-6.png",
    avatar: "/src/assets/images/avatar-6.png",
  },
  {
    id: 7,
    title: "Bộ quần áo xanh",
    category: "CLOTHES",
    city: "NA",
    district: "TP Vinh",
    location: "TP Vinh, Nghệ An",
    date: "27 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-7.png",
    avatar: "/src/assets/images/avatar-7.png",
  },
  {
    id: 8,
    title: "Áo len kem",
    category: "CLOTHES",
    city: "HP",
    district: "Lê Chân",
    location: "Lê Chân, Hải Phòng",
    date: "22 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-8.jpg",
    avatar: "/src/assets/images/avatar-8.png",
  },
  {
    id: 9,
    title: "Giày thể thao",
    category: "CLOTHES",
    city: "PT",
    district: "Việt Trì",
    location: "Việt Trì, Phú Thọ",
    date: "11 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-9.png",
    avatar: "/src/assets/images/avatar-9.png",
  },
  {
    id: 10,
    title: "Giày sandal nữ",
    category: "CLOTHES",
    city: "PT",
    district: "Thanh Ba",
    location: "Thanh Ba, Phú Thọ",
    date: "18 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-10.png",
    avatar: "/src/assets/images/avatar-7.png",
  },
  {
    id: 11,
    title: "Quạt điện",
    category: "HOME",
    city: "HB",
    district: "Hòa Bình",
    location: "Hòa Bình, Hòa Bình",
    date: "26 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-11.png",
    avatar: "/src/assets/images/avatar-8.png",
  },
  {
    id: 12,
    title: "Bình giữ nhiệt",
    category: "HOME",
    city: "BN",
    district: "TP Bắc Ninh",
    location: "TP Bắc Ninh, Bắc Ninh",
    date: "13 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-12.png",
    avatar: "/src/assets/images/avatar-5.png",
  },
  {
    id: 13,
    title: "Quần short",
    category: "OTHER",
    city: "HB",
    district: "Kim Bôi",
    location: "Kim Bôi, Hòa Bình",
    date: "15 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-8.jpg",
    avatar: "/src/assets/images/avatar-2.png",
  },
  {
    id: 14,
    title: "Cardigan vàng",
    category: "OTHER",
    city: "BN",
    district: "Quế Võ",
    location: "Quế Võ, Bắc Ninh",
    date: "14 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-1.png",
    avatar: "/src/assets/images/avatar-2.png",
  },
  {
    id: 15,
    title: "Bộ quần áo xanh",
    category: "OTHER",
    city: "LD",
    district: "Đơn Dương",
    location: "Đơn Dương, Lâm Đồng",
    date: "28 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-2.png",
    avatar: "/src/assets/images/avatar-3.png",
  },
  {
    id: 16,
    title: "Áo len kem",
    category: "CLOTHES",
    city: "LD",
    district: "Đơn Dương",
    location: "Đơn Dương, Lâm Đồng",
    date: "17 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-3.png",
    avatar: "/src/assets/images/avatar-4.png",
  },
  {
    id: 17,
    title: "Cardigan vàng",
    category: "OTHER",
    city: "HN",
    district: "Hoàng Mai",
    location: "Hoàng Mai, Hà Nội",
    date: "14 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-1.png",
    avatar: "/src/assets/images/avatar-2.png",
  },
  {
    id: 18,
    title: "Bộ quần áo xanh",
    category: "OTHER",
    city: "HN",
    district: "Ba Đình",
    location: "Ba Đình, Hà Nội",
    date: "28 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-2.png",
    avatar: "/src/assets/images/avatar-3.png",
  },
  {
    id: 19,
    title: "Áo len kem",
    category: "CLOTHES",
    city: "HN",
    district: "Cầu Giấy",
    location: "Cầu Giấy, Hà Nội",
    date: "17 tháng 2, 2025",
    thumbnail: "/src/assets/images/product-6.png",
    avatar: "/src/assets/images/avatar-2.png",
  },
];

export interface CategoryOption {
  name: string;
  code: string;
}

export const CATEGORIES_OPTION: CategoryOption[] = [
  { name: "Quần/áo", code: "CLOTHES" },
  { name: "Đồ gia dụng", code: "HOME" },
  { name: "Đồ điện tử", code: "ELEC" },
  { name: "Khác", code: "OTHER" },
];
