/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BInput: typeof import('./components/base/BInput/index.vue')['default']
    BoxCard: typeof import('./components/base/BoxCard/index.vue')['default']
    BSelect: typeof import('./components/base/BSelect/index.vue')['default']
    BTextarea: typeof import('./components/base/BTextarea/index.vue')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    Input: typeof import('./components/base/Input/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/base/Select/index.vue')['default']
    Sidebar: typeof import('./components/Sidebar/index.vue')['default']
  }
}
